# Generated by Django 3.2.5 on 2021-08-17 11:42

from django.db import migrations, models
import django.db.models.deletion


def set_cvs_owners(apps, schema_editor):
    """Set owners to CVs and remove CVs without owners."""
    CV = apps.get_model('users', 'CV')
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(cv__isnull=False).all():
        CV.objects.filter(pk=user.cv.pk).update(owner=user)
    CV.objects.filter(owner__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.OneToOneField(
                blank=True, help_text='Stores a CV.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_owner',
                to='users.cv',
                verbose_name='CV'
            ),
        ),
        migrations.AddField(
            model_name='cv',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cvs',
                to='users.user',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_cvs_owners),
        migrations.AlterField(
            model_name='cv',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cvs',
                to='users.user'
            ),
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
