# Generated by Django 3.2.5 on 2021-08-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210726_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_from', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_to', to=settings.AUTH_USER_MODEL, verbose_name='Reported user'),
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('created_by', 'reported')},
        ),
    ]
