# Generated by Django 3.2.5 on 2021-08-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210803_0923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('user', 'banned_user')},
        ),
    ]
