# Generated by Django 3.2.5 on 2021-08-19 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='Comment text')),
                ('author', models.ForeignKey(help_text='Indicates the author of the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent_comment', models.ForeignKey(blank=True, default=None, help_text='Allows to create a tree-like structure of comments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.comment', verbose_name='Parent of comment')),
                ('startup', models.ForeignKey(help_text='Comment about Startup', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='startups.startup', verbose_name='Startup')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
