from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/registration/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/registration/password_reset.html",
        ),
        name="reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/registration/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        views.SignUpView.as_view(),
        name="signup"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "account/",
        views.UserDetailView.as_view(),
        name="account"
    ),
    path(
        "account/update/",
        views.UserUpdateView.as_view(),
        name="account_update"
    ),
    path(
        "account/cvs",
        views.CurrentUserCVsView.as_view(),
        name="account_cvs"
    ),
    path(
        "account/cvs/<int:pk>",
        views.CurrentUserCVDetailView.as_view(),
        name="account_cv_detail"
    ),
    path(
        "account/cvs/<int:pk>/update/",
        views.CurrentUserCVUpdateView.as_view(),
        name="update_cv"
    ),
    path(
        "account/cvs/create/",
        views.CurrentUserCVCreateView.as_view(),
        name="create_cv",
    ),
    path(
        "account/cvs/<int:pk>/delete/",
        views.CurrentUserCVDeleteView.as_view(),
        name="delete_cv",
    ),
    path(
        "signup/<uid64>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate-account",
    ),
    path(
        "cvs/",
        views.CVsListView.as_view(),
        name="cvs",
    ),
    path(
        "cvs/<int:pk>",
        views.CVsDetailView.as_view(),
        name="cv_detail",
    ),
    path(
        "signup-complete/",
        views.ActivateAccountCompleteView.as_view(),
        name="activate_account_complete",
    ),
    path(
        "signup-done/",
        views.ActivateAccountDoneView.as_view(),
        name="activate_account_done",
    ),
    path(
        "signup-invalid/",
        views.ActivateAccountInvalidView.as_view(),
        name="activate_account_invalid",
    ),
    path(
        "profiles/<int:pk>",
        views.UserProfileView.as_view(),
        name="user_profile",
    ),
]
