# Generated by Django 3.2.5 on 2021-08-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='update_status_task',
            field=models.OneToOneField(blank=True, help_text='Celery task of updating status to closed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup', to='django_celery_beat.periodictask', verbose_name='Celery task for closing startup'),
        ),
    ]
