# Generated by Django 3.2.5 on 2021-08-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20210826_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(help_text='Vacancy Title', max_length=100, verbose_name='Title'),
        ),
    ]
