# Generated by Django 3.2.5 on 2021-08-26 13:12

import config.settings.common.paths
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210826_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='courses/default_course_img/default.jpeg', upload_to=config.settings.common.paths._default_media_path, verbose_name='Image'),
        ),
    ]
