# Generated by Django 3.2.5 on 2021-08-02 04:42

import ckeditor.fields
import django.contrib.postgres.fields.citext
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models

import apps.users.models
import apps.users.validators
import config.settings.common.paths


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('email', django.contrib.postgres.fields.citext.CICharField(max_length=254, unique=True, validators=[apps.users.validators.validate_email_domain], verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, max_length=512, null=True, upload_to=config.settings.common.paths._default_media_path, verbose_name='Profile image')),
                ('bio', ckeditor.fields.RichTextField(blank=True, max_length=1024, verbose_name='Bio')),
                ('github_username', models.SlugField(default='', max_length=39, verbose_name='GitHub username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.', verbose_name='Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='user link', max_length=100, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'User link',
                'verbose_name_plural': 'User links',
                'ordering': ('title',),
            },
        ),
    ]
