# Generated by Django 3.2.5 on 2021-08-24 06:44


import config.settings.common.paths
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(default='users/default_avatar/default.jpg', max_length=512, upload_to=config.settings.common.paths._default_media_path, verbose_name='Profile image'),
        ),
    ]
