# Generated by Django 3.2.5 on 2021-07-26 06:16

import apps.map.models.meeting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='deadline',
            field=models.DateTimeField(default=apps.map.models.meeting.get_default_deadline, verbose_name='Delete time'),
        ),
    ]
