# Generated by Django 3.2.5 on 2021-07-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
        ('map', '0002_alter_meeting_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='dialog',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='dialogs.dialog', verbose_name='Dialog'),
            preserve_default=False,
        ),
    ]
